# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            pclalv
tagline:          ''
description:      ''
url:              http://pclalv.github.io/
baseurl:          /

author:
  name:           'Paul Alvarez'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pclalv/pclalv.github.io
